language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y libvtk5-dev libvtk5.8
  - sudo apt-get install -qq gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo apt-get install -y openmpi-bin libopenmpi-dev
  - sudo apt-get install -y libparmetis-dev
  - wget http://bitbucket.org/eigen/eigen/get/2.0.17.tar.gz
  - tar zxvf 2.0.17.tar.gz 
  - pushd eigen-eigen-b23437e61a07/
  - mkdir build
  - pushd build
  - cmake ../
  - make install
  - popd
  - popd
compiler:
  - gcc
# Change this to your needs
env:
  - ENABLE_VTK=FALSE
  - ENABLE_VTK=TRUE
  - ENABLE_MPI=FALSE
  - ENABLE_MPI=TRUE
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd tests/
  - make
  - make test ARGS="-v"

