language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvtk5-dev libvtk5.8
compiler:
  - gcc
  - clang
# Change this to your needs
script: cmake . && make && make -c tests test

