language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvtk5-dev libvtk5.8
  - sudo apt-get install -y openmpi-bin libopenmpi-dev
  - sudo apt-get install -y libparmetis-dev
install: travis_wait mvn install
compiler:
  - gcc
# Change this to your needs
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd tests/
  - make
  - travis_wait make test

